uid = 1
gid = 2
log_dir = "/tmp2"
cat_stat_dir = "/var/log"
zk_acl = ("a", "b")
zk_auth = ("digest", "xp", "123")
iostat_stat_path = "/tmp/ps"
zk_hosts = "127.0.0.1:21812"
zk_lock_dir = "lock/222"
zk_node_id = "123"
zk_record_dir = "rec/"
zk_tx_dir = "t/"
zk_seq_dir = "sq/"
zk_tx_timeout = 3
rp_cli_nwr = (4, 3, 2)
rp_cli_ak_sk = ("access", "secret")
ec_block_port = 6001
inner_ip_patterns = [123]
